networks: 
  phpinfo-3: 
    internal: true
services:
  phpinfo-3:
    deploy:
      #varios contenedores en la misma VM
      mode: replicated
      #un unico contenedor x cada VM
      #mode: global
      placement: 
        constraints:
        - node.role == worker
      replicas: 2
      resources: 
        limits:
          cpus: "0.1"
          memory: 100m
        reservations:
          cpus: "0.1"
          memory: 100m
    expose: 
    - 8080
    healthcheck:
      interval: 20s
      retries: 3
      start_period: 10s
      test: php -r "print file_get_contents('http://localhost:8080/');"
      timeout: 1s
    image: lherrerom/phpinfo-3:latest 
    networks:
    - phpinfo-3
    ports: 
    - 8080:8080
version: "3.8" 

        
